<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Diary.GUIBase\Diary.GUIBase.csproj" />
    <ProjectReference Include="..\Diary.ModuleBase\Diary.ModuleBase.csproj" />
  </ItemGroup>
</Project>
