<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CETCompat>false</CETCompat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="RestSharp.Serializers.NewtonsoftJson" Version="114.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diary.Core\Diary.Core.csproj" />
    <ProjectReference Include="..\Diary.Database\Diary.Database.csproj" />
    <ProjectReference Include="..\Diary.PluginBase\Diary.PluginBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Diary.RedMineTests" />
  </ItemGroup>

</Project>
