<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Diary.Script.Runtime\Diary.Script.Runtime.csproj" />
    <ProjectReference Include="..\Diary.ScriptBase\Diary.ScriptBase.csproj" />
    <ProjectReference Include="..\Diary.Database\Diary.Database.csproj" />
    <ProjectReference Include="..\Diary.Core\Diary.Core.csproj" />
    <ProjectReference Include="..\Diary.PluginBase\Diary.PluginBase.csproj" />
  </ItemGroup>
</Project>
