<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Diary.Database\Diary.Database.csproj" />
    <ProjectReference Include="..\Diary.Jira\Diary.Jira.csproj" />
  </ItemGroup>
</Project>
