<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.3.10" />
      <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.10" />
      <PackageReference Include="TreeDataGrid.Avalonia" Version="11.3.0" />
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
      <PackageReference Include="Irihi.Ursa" Version="1.14.1" />
      <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="1.14.1" />
      <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.0.0-rc6.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
      <PackageReference Include="Projektanker.Icons.Avalonia" Version="9.6.2" />
      <PackageReference Include="Projektanker.Icons.Avalonia.FontAwesome" Version="9.6.2" />
      <PackageReference Include="Projektanker.Icons.Avalonia.MaterialDesign" Version="9.6.2" />
      <PackageReference Include="Semi.Avalonia" Version="11.3.7.2" />
      <PackageReference Include="Semi.Avalonia.ColorPicker" Version="11.3.7.2" />
      <PackageReference Include="Semi.Avalonia.DataGrid" Version="11.3.7.2" />
      <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.9" />
      <PackageReference Include="Xaml.Behaviors.Interactivity" Version="11.3.9" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Views\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Diary.Core\Diary.Core.csproj" />
      <ProjectReference Include="..\Diary.Database\Diary.Database.csproj" />
    </ItemGroup>

</Project>
